$(document).ready(function () {
	$.getJSON("config/urls.json")
		.done(function (json) {
      url = json.urls;
			$.post(url.project_table + "/query", {
          where: "1=1",
          outFields: "Division",
          returnGeometry: false,
          orderByFields: 'Division',
          returnDistinctValues: true,
          f: 'pjson'
        })
        .done(function (data) {
          var divisions = $.parseJSON(data);
          var divisionSelect = $('#division');
          $(divisions.features).each(function () {
            divisionSelect.append(
              $('<option></option>').val(this.attributes.Division).html(this.attributes.Division)
            );
          });

        });

			$.post(url.MPOs + "/query", {
          where: "1=1",
          outFields: "MPO",
          returnGeometry: false,
          orderByFields: 'MPO',
          f: 'pjson'
        })
        .done(function (data) {
          var mpos = $.parseJSON(data);
          var mpoSelect = $('#mpoSelect');
          $(mpos.features).each(function () {
            mpoSelect.append(
              $('<option></option>').val(this.attributes.MPO).html(this.attributes.MPO)
            );
          });

        });

			$.post(url.Towns + "/query", {
          where: "1=1",
          outFields: "TOWN, TOWN_ID",
          returnGeometry: false,
          orderByFields: 'TOWN_ID',
          f: 'pjson'
        })
        .done(function (data) {
          var towns = $.parseJSON(data);
          var townsSelect = $('#townSelect');
          $(towns.features).each(function () {
            townsSelect.append(
              $('<option></option>').val(this.attributes.TOWN_ID).html(this.attributes.TOWN)
            );
          });

        });

			programList = [];

			$.post(url.project_table + "/query", {
          where: "1=1",
          outFields: "Division, Program",
          returnGeometry: false,
          orderByFields: 'Program',
          returnDistinctValues: true,
          f: 'pjson'
        })
        .done(function (data) {
          var programs = $.parseJSON(data);
          var programSelector = $('#programs');
          $(programs.features).each(function () {
            programList.push(this.attributes.Program);
            programSelector.append(
              $('<option></option>').val(this.attributes.Program).html(this.attributes.Program).attr("division", this.attributes.Division)
            );
          });
          getPrograms();
        });

		  function getPrograms() {
				$("#programs").val("");
		    $("#programs option").filter(function () {
		      $(this).toggle($(this).attr("division") == $('#division').val() || $(this).attr("division") == "All");
		    });
		  };

		  $("#division").change(function () {
		    getPrograms();
		  });

		})

    .fail(function (jqxhr, textStatus, error) {
      var err = textStatus + ", " + error;
    });


		dict_townID = {
			"1": {"town":"Abington","MPO":"Old Colony","RTA":"BAT"},
			"2": {"town":"Acton","MPO":"Boston Region","RTA":"LRTA"},
			"3": {"town":"Acushnet","MPO":"Southeastern Massachusetts","RTA":"SRTA"},
			"4": {"town":"Adams","MPO":"Berkshire","RTA":"BRTA"},
			"5": {"town":"Agawam","MPO":"Pioneer Valley","RTA":"PVTA"},
			"6": {"town":"Alford","MPO":"Berkshire","RTA":"NONE"},
			"7": {"town":"Amesbury","MPO":"Merrimack Valley","RTA":"MVRTA"},
			"8": {"town":"Amherst","MPO":"Pioneer Valley","RTA":"PVTA"},
			"9": {"town":"Andover","MPO":"Merrimack Valley","RTA":"MVRTA"},
			"10": {"town":"Arlington","MPO":"Boston Region","RTA":"MBTA"},
			"11": {"town":"Ashburnham","MPO":"Montachusett","RTA":"MRTA"},
			"12": {"town":"Ashby","MPO":"Montachusett","RTA":"MRTA"},
			"13": {"town":"Ashfield","MPO":"Franklin","RTA":"FRTA"},
			"14": {"town":"Ashland","MPO":"Boston Region","RTA":"MBTA"},
			"15": {"town":"Athol","MPO":"Montachusett","RTA":"FRTA"},
			"16": {"town":"Attleboro","MPO":"Southeastern Massachusetts","RTA":"GATRA"},
			"17": {"town":"Auburn","MPO":"Central Massachusetts","RTA":"WRTA"},
			"18": {"town":"Avon","MPO":"Old Colony","RTA":"BAT"},
			"19": {"town":"Ayer","MPO":"Montachusett","RTA":"MRTA"},
			"20": {"town":"Barnstable","MPO":"Cape Cod","RTA":"CCRTA"},
			"21": {"town":"Barre","MPO":"Central Massachusetts","RTA":"WRTA"},
			"22": {"town":"Becket","MPO":"Berkshire","RTA":"NONE"},
			"23": {"town":"Bedford","MPO":"Boston Region","RTA":"MBTA"},
			"24": {"town":"Belchertown","MPO":"Pioneer Valley","RTA":"PVTA"},
			"25": {"town":"Bellingham","MPO":"Boston Region","RTA":"NONE"},
			"26": {"town":"Belmont","MPO":"Boston Region","RTA":"MBTA"},
			"27": {"town":"Berkley","MPO":"Southeastern Massachusetts","RTA":"NONE"},
			"28": {"town":"Berlin","MPO":"Central Massachusetts","RTA":"WRTA"},
			"29": {"town":"Bernardston","MPO":"Franklin","RTA":"FRTA"},
			"30": {"town":"Beverly","MPO":"Boston Region","RTA":"MBTA"},
			"31": {"town":"Billerica","MPO":"Northern Middlesex","RTA":"LRTA"},
			"32": {"town":"Blackstone","MPO":"Central Massachusetts","RTA":"NONE"},
			"34": {"town":"Bolton","MPO":"Boston Region","RTA":"NONE"},
			"33": {"town":"Blandford","MPO":"Pioneer Valley","RTA":"NONE"},
			"35": {"town":"Boston","MPO":"Boston Region","RTA":"MBTA"},
			"36": {"town":"Bourne","MPO":"Cape Cod","RTA":"CCRTA"},
			"37": {"town":"Boxborough","MPO":"Boston Region","RTA":"NONE"},
			"38": {"town":"Boxford","MPO":"Merrimack Valley","RTA":"MVRTA"},
			"39": {"town":"Boylston","MPO":"Central Massachusetts","RTA":"WRTA"},
			"40": {"town":"Braintree","MPO":"Boston Region","RTA":"MBTA"},
			"41": {"town":"Brewster","MPO":"Cape Cod","RTA":"CCRTA"},
			"42": {"town":"Bridgewater","MPO":"Old Colony","RTA":"BAT"},
			"43": {"town":"Brimfield","MPO":"Pioneer Valley","RTA":"WRTA"},
			"44": {"town":"Brockton","MPO":"Old Colony","RTA":"BAT"},
			"45": {"town":"Brookfield","MPO":"Central Massachusetts","RTA":"WRTA"},
			"46": {"town":"Brookline","MPO":"Boston Region","RTA":"MBTA"},
			"47": {"town":"Buckland","MPO":"Franklin","RTA":"FRTA"},
			"48": {"town":"Burlington","MPO":"Boston Region","RTA":"MBTA"},
			"49": {"town":"Cambridge","MPO":"Boston Region","RTA":"MBTA"},
			"50": {"town":"Canton","MPO":"Boston Region","RTA":"MBTA"},
			"51": {"town":"Carlisle","MPO":"Boston Region","RTA":"NONE"},
			"52": {"town":"Carver","MPO":"Southeastern Massachusetts","RTA":"GATRA"},
			"53": {"town":"Charlemont","MPO":"Franklin","RTA":"FRTA"},
			"54": {"town":"Charlton","MPO":"Central Massachusetts","RTA":"WRTA"},
			"55": {"town":"Chatham","MPO":"Cape Cod","RTA":"CCRTA"},
			"56": {"town":"Chelmsford","MPO":"Northern Middlesex","RTA":"LRTA"},
			"57": {"town":"Chelsea","MPO":"Boston Region","RTA":"MBTA"},
			"58": {"town":"Cheshire","MPO":"Berkshire","RTA":"BRTA"},
			"59": {"town":"Chester","MPO":"Pioneer Valley","RTA":"NONE"},
			"60": {"town":"Chesterfield","MPO":"Pioneer Valley","RTA":"FRTA"},
			"61": {"town":"Chicopee","MPO":"Pioneer Valley","RTA":"PVTA"},
			"62": {"town":"Chilmark","MPO":"Martha's Vineyard","RTA":"VTA"},
			"63": {"town":"Clarksburg","MPO":"Berkshire","RTA":"BRTA"},
			"64": {"town":"Clinton","MPO":"Montachusett","RTA":"WRTA"},
			"65": {"town":"Cohasset","MPO":"Boston Region","RTA":"MBTA"},
			"66": {"town":"Colrain","MPO":"Franklin","RTA":"FRTA"},
			"67": {"town":"Concord","MPO":"Boston Region","RTA":"MBTA"},
			"68": {"town":"Conway","MPO":"Franklin","RTA":"FRTA"},
			"69": {"town":"Cummington","MPO":"Pioneer Valley","RTA":"FRTA"},
			"70": {"town":"Dalton","MPO":"Berkshire","RTA":"BRTA"},
			"71": {"town":"Danvers","MPO":"Boston Region","RTA":"MBTA"},
			"72": {"town":"Dartmouth","MPO":"Southeastern Massachusetts","RTA":"SRTA"},
			"73": {"town":"Dedham","MPO":"Boston Region","RTA":"MBTA"},
			"74": {"town":"Deerfield","MPO":"Franklin","RTA":"FRTA"},
			"75": {"town":"Dennis","MPO":"Cape Cod","RTA":"CCRTA"},
			"76": {"town":"Dighton","MPO":"Southeastern Massachusetts","RTA":"GATRA"},
			"77": {"town":"Douglas","MPO":"Central Massachusetts","RTA":"WRTA"},
			"78": {"town":"Dover","MPO":"Boston Region","RTA":"MBTA"},
			"79": {"town":"Dracut","MPO":"Northern Middlesex","RTA":"LRTA"},
			"80": {"town":"Dudley","MPO":"Central Massachusetts","RTA":"WRTA"},
			"81": {"town":"Dunstable","MPO":"Northern Middlesex","RTA":"NONE"},
			"82": {"town":"Duxbury","MPO":"Old Colony","RTA":"MBTA"},
			"83": {"town":"East Bridgewater","MPO":"Old Colony","RTA":"BAT"},
			"84": {"town":"East Brookfield","MPO":"Central Massachusetts","RTA":"WRTA"},
			"85": {"town":"East Longmeadow","MPO":"Pioneer Valley","RTA":"PVTA"},
			"86": {"town":"Eastham","MPO":"Cape Cod","RTA":"CCRTA"},
			"87": {"town":"Easthampton","MPO":"Pioneer Valley","RTA":"PVTA"},
			"88": {"town":"Easton","MPO":"Old Colony","RTA":"BAT"},
			"89": {"town":"Edgartown","MPO":"Martha's Vineyard","RTA":"VTA"},
			"90": {"town":"Egremont","MPO":"Berkshire","RTA":"NONE"},
			"91": {"town":"Erving","MPO":"Franklin","RTA":"FRTA"},
			"92": {"town":"Essex","MPO":"Boston Region","RTA":"CATA"},
			"93": {"town":"Everett","MPO":"Boston Region","RTA":"MBTA"},
			"94": {"town":"Fairhaven","MPO":"Southeastern Massachusetts","RTA":"SRTA"},
			"95": {"town":"Fall River","MPO":"Southeastern Massachusetts","RTA":"SRTA"},
			"96": {"town":"Falmouth","MPO":"Cape Cod","RTA":"CCRTA"},
			"97": {"town":"Fitchburg","MPO":"Montachusett","RTA":"MRTA"},
			"98": {"town":"Florida","MPO":"Berkshire","RTA":"NONE"},
			"99": {"town":"Foxborough","MPO":"Boston Region","RTA":"NONE"},
			"100": {"town":"Framingham","MPO":"Boston Region","RTA":"MBTA"},
			"101": {"town":"Franklin","MPO":"Boston Region","RTA":"NONE"},
			"102": {"town":"Freetown","MPO":"Southeastern Massachusetts","RTA":"SRTA"},
			"103": {"town":"Gardner","MPO":"Montachusett","RTA":"MRTA"},
			"104": {"town":"Aquinnah","MPO":"Martha's Vineyard","RTA":"VTA"},
			"105": {"town":"Georgetown","MPO":"Merrimack Valley","RTA":"MVRTA"},
			"106": {"town":"Gill","MPO":"Franklin","RTA":"FRTA"},
			"107": {"town":"Gloucester","MPO":"Boston Region","RTA":"CATA"},
			"108": {"town":"Goshen","MPO":"Pioneer Valley","RTA":"FRTA"},
			"109": {"town":"Gosnold","MPO":"Martha's Vineyard","RTA":"NONE"},
			"110": {"town":"Grafton","MPO":"Central Massachusetts","RTA":"WRTA"},
			"111": {"town":"Granby","MPO":"Pioneer Valley","RTA":"PVTA"},
			"112": {"town":"Granville","MPO":"Pioneer Valley","RTA":"NONE"},
			"113": {"town":"Great Barrington","MPO":"Berkshire","RTA":"BRTA"},
			"114": {"town":"Greenfield","MPO":"Franklin","RTA":"GMTA"},
			"115": {"town":"Groton","MPO":"Montachusett","RTA":"LRTA"},
			"116": {"town":"Groveland","MPO":"Merrimack Valley","RTA":"MVRTA"},
			"117": {"town":"Hadley","MPO":"Pioneer Valley","RTA":"PVTA"},
			"118": {"town":"Halifax","MPO":"Old Colony","RTA":"NONE"},
			"119": {"town":"Hamilton","MPO":"Boston Region","RTA":"MBTA"},
			"120": {"town":"Hampden","MPO":"Pioneer Valley","RTA":"PVTA"},
			"121": {"town":"Hancock","MPO":"Berkshire","RTA":"NONE"},
			"122": {"town":"Hanover","MPO":"Old Colony","RTA":"MBTA"},
			"123": {"town":"Hanson","MPO":"Old Colony","RTA":"NONE"},
			"124": {"town":"Hardwick","MPO":"Central Massachusetts","RTA":"MRTA"},
			"125": {"town":"Harvard","MPO":"Montachusett","RTA":"NONE"},
			"126": {"town":"Harwich","MPO":"Cape Cod","RTA":"CCRTA"},
			"127": {"town":"Hatfield","MPO":"Pioneer Valley","RTA":"NONE"},
			"128": {"town":"Haverhill","MPO":"Merrimack Valley","RTA":"MVRTA"},
			"129": {"town":"Hawley","MPO":"Franklin","RTA":"FRTA"},
			"130": {"town":"Heath","MPO":"Franklin","RTA":"FRTA"},
			"131": {"town":"Hingham","MPO":"Boston Region","RTA":"MBTA"},
			"132": {"town":"Hinsdale","MPO":"Berkshire","RTA":"BRTA"},
			"133": {"town":"Holbrook","MPO":"Boston Region","RTA":"MBTA"},
			"134": {"town":"Holden","MPO":"Central Massachusetts","RTA":"WRTA"},
			"135": {"town":"Holland","MPO":"Pioneer Valley","RTA":"WRTA"},
			"136": {"town":"Holliston","MPO":"Boston Region","RTA":"NONE"},
			"137": {"town":"Holyoke","MPO":"Pioneer Valley","RTA":"PVTA"},
			"138": {"town":"Hopedale","MPO":"Central Massachusetts","RTA":"NONE"},
			"139": {"town":"Hopkinton","MPO":"Boston Region","RTA":"NONE"},
			"140": {"town":"Hubbardston","MPO":"Montachusett","RTA":"MRTA"},
			"141": {"town":"Hudson","MPO":"Boston Region","RTA":"NONE"},
			"142": {"town":"Hull","MPO":"Boston Region","RTA":"MBTA"},
			"143": {"town":"Huntington","MPO":"Pioneer Valley","RTA":"FRTA"},
			"144": {"town":"Ipswich","MPO":"Boston Region","RTA":"CATA"},
			"145": {"town":"Kingston","MPO":"Old Colony","RTA":"GATRA"},
			"146": {"town":"Lakeville","MPO":"Southeastern Massachusetts","RTA":"GATRA"},
			"147": {"town":"Lancaster","MPO":"Montachusett","RTA":"MRTA"},
			"148": {"town":"Lanesborough","MPO":"Berkshire","RTA":"BRTA"},
			"149": {"town":"Lawrence","MPO":"Merrimack Valley","RTA":"MVRTA"},
			"150": {"town":"Lee","MPO":"Berkshire","RTA":"BRTA"},
			"151": {"town":"Leicester","MPO":"Central Massachusetts","RTA":"WRTA"},
			"152": {"town":"Lenox","MPO":"Berkshire","RTA":"BRTA"},
			"153": {"town":"Leominster","MPO":"Montachusett","RTA":"MRTA"},
			"154": {"town":"Leverett","MPO":"Franklin","RTA":"PVTA"},
			"155": {"town":"Lexington","MPO":"Boston Region","RTA":"MBTA"},
			"156": {"town":"Leyden","MPO":"Franklin","RTA":"NONE"},
			"157": {"town":"Lincoln","MPO":"Boston Region","RTA":"MBTA"},
			"158": {"town":"Littleton","MPO":"Boston Region","RTA":"MRTA"},
			"159": {"town":"Longmeadow","MPO":"Pioneer Valley","RTA":"PVTA"},
			"160": {"town":"Lowell","MPO":"Northern Middlesex","RTA":"LRTA"},
			"161": {"town":"Ludlow","MPO":"Pioneer Valley","RTA":"PVTA"},
			"162": {"town":"Lunenburg","MPO":"Montachusett","RTA":"MRTA"},
			"163": {"town":"Lynn","MPO":"Boston Region","RTA":"MBTA"},
			"164": {"town":"Lynnfield","MPO":"Boston Region","RTA":"MBTA"},
			"165": {"town":"Malden","MPO":"Boston Region","RTA":"MBTA"},
			"166": {"town":"Manchester","MPO":"Boston Region","RTA":"MBTA"},
			"167": {"town":"Mansfield","MPO":"Southeastern Massachusetts","RTA":"GATRA"},
			"168": {"town":"Marblehead","MPO":"Boston Region","RTA":"MBTA"},
			"169": {"town":"Marion","MPO":"Southeastern Massachusetts","RTA":"NONE"},
			"170": {"town":"Marlborough","MPO":"Boston Region","RTA":"WRTA"},
			"171": {"town":"Marshfield","MPO":"Boston Region","RTA":"MBTA"},
			"172": {"town":"Mashpee","MPO":"Cape Cod","RTA":"CCRTA"},
			"173": {"town":"Mattapoisett","MPO":"Southeastern Massachusetts","RTA":"SRTA"},
			"174": {"town":"Maynard","MPO":"Boston Region","RTA":"NONE"},
			"175": {"town":"Medfield","MPO":"Boston Region","RTA":"MBTA"},
			"176": {"town":"Medford","MPO":"Boston Region","RTA":"MBTA"},
			"177": {"town":"Medway","MPO":"Boston Region","RTA":"NONE"},
			"178": {"town":"Melrose","MPO":"Boston Region","RTA":"MBTA"},
			"179": {"town":"Mendon","MPO":"Central Massachusetts","RTA":"NONE"},
			"180": {"town":"Merrimac","MPO":"Merrimack Valley","RTA":"MVRTA"},
			"181": {"town":"Methuen","MPO":"Merrimack Valley","RTA":"MVRTA"},
			"182": {"town":"Middleborough","MPO":"Southeastern Massachusetts","RTA":"GATRA"},
			"183": {"town":"Middlefield","MPO":"Pioneer Valley","RTA":"FRTA"},
			"184": {"town":"Middleton","MPO":"Boston Region","RTA":"MBTA"},
			"185": {"town":"Milford","MPO":"Boston Region","RTA":"NONE"},
			"186": {"town":"Millbury","MPO":"Central Massachusetts","RTA":"WRTA"},
			"187": {"town":"Millis","MPO":"Boston Region","RTA":"MBTA"},
			"188": {"town":"Millville","MPO":"Central Massachusetts","RTA":"NONE"},
			"189": {"town":"Milton","MPO":"Boston Region","RTA":"MBTA"},
			"190": {"town":"Monroe","MPO":"Franklin","RTA":"NONE"},
			"191": {"town":"Monson","MPO":"Pioneer Valley","RTA":"NONE"},
			"192": {"town":"Montague","MPO":"Franklin","RTA":"GMTA"},
			"193": {"town":"Monterey","MPO":"Berkshire","RTA":"NONE"},
			"194": {"town":"Montgomery","MPO":"Pioneer Valley","RTA":"FRTA"},
			"195": {"town":"Mount Washington","MPO":"Berkshire","RTA":"NONE"},
			"196": {"town":"Nahant","MPO":"Boston Region","RTA":"MBTA"},
			"197": {"town":"Nantucket","MPO":"Nantucket","RTA":"NRTA"},
			"198": {"town":"Natick","MPO":"Boston Region","RTA":"MBTA"},
			"199": {"town":"Needham","MPO":"Boston Region","RTA":"MBTA"},
			"200": {"town":"New Ashford","MPO":"Berkshire","RTA":"NONE"},
			"201": {"town":"New Bedford","MPO":"Southeastern Massachusetts","RTA":"SRTA"},
			"202": {"town":"New Braintree","MPO":"Central Massachusetts","RTA":"WRTA"},
			"203": {"town":"New Marlborough","MPO":"Berkshire","RTA":"NONE"},
			"204": {"town":"New Salem","MPO":"Franklin","RTA":"FRTA"},
			"205": {"town":"Newbury","MPO":"Merrimack Valley","RTA":"MVRTA"},
			"206": {"town":"Newburyport","MPO":"Merrimack Valley","RTA":"MVRTA"},
			"207": {"town":"Newton","MPO":"Boston Region","RTA":"MBTA"},
			"208": {"town":"Norfolk","MPO":"Boston Region","RTA":"MBTA"},
			"209": {"town":"North Adams","MPO":"Berkshire","RTA":"BRTA"},
			"210": {"town":"North Andover","MPO":"Merrimack Valley","RTA":"MVRTA"},
			"211": {"town":"North Attleborough","MPO":"Southeastern Massachusetts","RTA":"GATRA"},
			"212": {"town":"North Brookfield","MPO":"Central Massachusetts","RTA":"WRTA"},
			"213": {"town":"North Reading","MPO":"Boston Region","RTA":"MBTA"},
			"214": {"town":"Northampton","MPO":"Pioneer Valley","RTA":"PVTA"},
			"215": {"town":"Northborough","MPO":"Central Massachusetts","RTA":"WRTA"},
			"216": {"town":"Northbridge","MPO":"Central Massachusetts","RTA":"NONE"},
			"217": {"town":"Northfield","MPO":"Franklin","RTA":"FRTA"},
			"218": {"town":"Norton","MPO":"Southeastern Massachusetts","RTA":"GATRA"},
			"219": {"town":"Norwell","MPO":"Boston Region","RTA":"MBTA"},
			"220": {"town":"Norwood","MPO":"Boston Region","RTA":"MBTA"},
			"221": {"town":"Oak Bluffs","MPO":"Martha's Vineyard","RTA":"VTA"},
			"222": {"town":"Oakham","MPO":"Central Massachusetts","RTA":"WRTA"},
			"223": {"town":"Orange","MPO":"Franklin","RTA":"FRTA"},
			"224": {"town":"Orleans","MPO":"Cape Cod","RTA":"CCRTA"},
			"225": {"town":"Otis","MPO":"Berkshire","RTA":"NONE"},
			"226": {"town":"Oxford","MPO":"Central Massachusetts","RTA":"WRTA"},
			"227": {"town":"Palmer","MPO":"Pioneer Valley","RTA":"NONE"},
			"228": {"town":"Paxton","MPO":"Central Massachusetts","RTA":"NONE"},
			"229": {"town":"Peabody","MPO":"Boston Region","RTA":"MBTA"},
			"230": {"town":"Pelham","MPO":"Pioneer Valley","RTA":"PVTA"},
			"231": {"town":"Pembroke","MPO":"Old Colony","RTA":"MBTA"},
			"232": {"town":"Pepperell","MPO":"Northern Middlesex","RTA":"LRTA"},
			"233": {"town":"Peru","MPO":"Berkshire","RTA":"NONE"},
			"234": {"town":"Petersham","MPO":"Montachusett","RTA":"FRTA"},
			"235": {"town":"Phillipston","MPO":"Montachusett","RTA":"FRTA"},
			"236": {"town":"Pittsfield","MPO":"Berkshire","RTA":"BRTA"},
			"237": {"town":"Plainfield","MPO":"Pioneer Valley","RTA":"FRTA"},
			"238": {"town":"Plainville","MPO":"Southeastern Massachusetts","RTA":"GATRA"},
			"239": {"town":"Plymouth","MPO":"Old Colony","RTA":"GATRA"},
			"240": {"town":"Plympton","MPO":"Old Colony","RTA":"NONE"},
			"241": {"town":"Princeton","MPO":"Central Massachusetts","RTA":"WRTA"},
			"242": {"town":"Provincetown","MPO":"Cape Cod","RTA":"CCRTA"},
			"243": {"town":"Quincy","MPO":"Boston Region","RTA":"MBTA"},
			"244": {"town":"Randolph","MPO":"Boston Region","RTA":"MBTA"},
			"245": {"town":"Raynham","MPO":"Southeastern Massachusetts","RTA":"GATRA"},
			"246": {"town":"Reading","MPO":"Boston Region","RTA":"MBTA"},
			"247": {"town":"Rehoboth","MPO":"Southeastern Massachusetts","RTA":"GATRA"},
			"248": {"town":"Revere","MPO":"Boston Region","RTA":"MBTA"},
			"249": {"town":"Richmond","MPO":"Berkshire","RTA":"BRTA"},
			"250": {"town":"Rochester","MPO":"Southeastern Massachusetts","RTA":"NONE"},
			"251": {"town":"Rockland","MPO":"Boston Region","RTA":"MBTA"},
			"252": {"town":"Rockport","MPO":"Boston Region","RTA":"CATA"},
			"253": {"town":"Rowe","MPO":"Franklin","RTA":"FRTA"},
			"254": {"town":"Rowley","MPO":"Merrimack Valley","RTA":"MVRTA"},
			"255": {"town":"Royalston","MPO":"Montachusett","RTA":"MRTA"},
			"256": {"town":"Russell","MPO":"Pioneer Valley","RTA":"FRTA"},
			"257": {"town":"Rutland","MPO":"Central Massachusetts","RTA":"WRTA"},
			"258": {"town":"Salem","MPO":"Boston Region","RTA":"MBTA"},
			"259": {"town":"Salisbury","MPO":"Merrimack Valley","RTA":"NONE"},
			"260": {"town":"Sandisfield","MPO":"Berkshire","RTA":"NONE"},
			"261": {"town":"Sandwich","MPO":"Cape Cod","RTA":"CCRTA"},
			"262": {"town":"Saugus","MPO":"Boston Region","RTA":"MBTA"},
			"263": {"town":"Savoy","MPO":"Berkshire","RTA":"NONE"},
			"264": {"town":"Scituate","MPO":"Boston Region","RTA":"MBTA"},
			"265": {"town":"Seekonk","MPO":"Southeastern Massachusetts","RTA":"GATRA"},
			"266": {"town":"Sharon","MPO":"Boston Region","RTA":"MBTA"},
			"267": {"town":"Sheffield","MPO":"Berkshire","RTA":"NONE"},
			"268": {"town":"Shelburne","MPO":"Franklin","RTA":"FRTA"},
			"269": {"town":"Sherborn","MPO":"Boston Region","RTA":"MBTA"},
			"270": {"town":"Shirley","MPO":"Montachusett","RTA":"MRTA"},
			"271": {"town":"Shrewsbury","MPO":"Central Massachusetts","RTA":"WRTA"},
			"272": {"town":"Shutesbury","MPO":"Franklin","RTA":"FRTA"},
			"273": {"town":"Somerset","MPO":"Southeastern Massachusetts","RTA":"SRTA"},
			"274": {"town":"Somerville","MPO":"Boston Region","RTA":"MBTA"},
			"275": {"town":"South Hadley","MPO":"Pioneer Valley","RTA":"PVTA"},
			"276": {"town":"Southampton","MPO":"Pioneer Valley","RTA":"FRTA"},
			"277": {"town":"Southborough","MPO":"Boston Region","RTA":"WRTA"},
			"278": {"town":"Southbridge","MPO":"Central Massachusetts","RTA":"WRTA"},
			"279": {"town":"Southwick","MPO":"Pioneer Valley","RTA":"FRTA"},
			"280": {"town":"Spencer","MPO":"Central Massachusetts","RTA":"WRTA"},
			"281": {"town":"Springfield","MPO":"Pioneer Valley","RTA":"PVTA"},
			"282": {"town":"Sterling","MPO":"Montachusett","RTA":"MRTA"},
			"283": {"town":"Stockbridge","MPO":"Berkshire","RTA":"BRTA"},
			"284": {"town":"Stoneham","MPO":"Boston Region","RTA":"MBTA"},
			"285": {"town":"Stoughton","MPO":"Old Colony","RTA":"BAT"},
			"286": {"town":"Stow","MPO":"Boston Region","RTA":"NONE"},
			"287": {"town":"Sturbridge","MPO":"Central Massachusetts","RTA":"WRTA"},
			"288": {"town":"Sudbury","MPO":"Boston Region","RTA":"MBTA"},
			"289": {"town":"Sunderland","MPO":"Franklin","RTA":"PVTA"},
			"290": {"town":"Sutton","MPO":"Central Massachusetts","RTA":"WRTA"},
			"291": {"town":"Swampscott","MPO":"Boston Region","RTA":"MBTA"},
			"292": {"town":"Swansea","MPO":"Southeastern Massachusetts","RTA":"SRTA"},
			"293": {"town":"Taunton","MPO":"Southeastern Massachusetts","RTA":"GATRA"},
			"294": {"town":"Templeton","MPO":"Montachusett","RTA":"MRTA"},
			"295": {"town":"Tewksbury","MPO":"Northern Middlesex","RTA":"LRTA"},
			"296": {"town":"Tisbury","MPO":"Martha's Vineyard","RTA":"VTA"},
			"297": {"town":"Tolland","MPO":"Pioneer Valley","RTA":"NONE"},
			"298": {"town":"Topsfield","MPO":"Boston Region","RTA":"MBTA"},
			"299": {"town":"Townsend","MPO":"Montachusett","RTA":"LRTA"},
			"300": {"town":"Truro","MPO":"Cape Cod","RTA":"CCRTA"},
			"301": {"town":"Tyngsborough","MPO":"Northern Middlesex","RTA":"LRTA"},
			"302": {"town":"Tyringham","MPO":"Berkshire","RTA":"NONE"},
			"303": {"town":"Upton","MPO":"Central Massachusetts","RTA":"NONE"},
			"304": {"town":"Uxbridge","MPO":"Central Massachusetts","RTA":"NONE"},
			"305": {"town":"Wakefield","MPO":"Boston Region","RTA":"MBTA"},
			"306": {"town":"Wales","MPO":"Pioneer Valley","RTA":"WRTA"},
			"307": {"town":"Walpole","MPO":"Boston Region","RTA":"MBTA"},
			"308": {"town":"Waltham","MPO":"Boston Region","RTA":"MBTA"},
			"309": {"town":"Ware","MPO":"Pioneer Valley","RTA":"PVTA"},
			"310": {"town":"Wareham","MPO":"Southeastern Massachusetts","RTA":"GATRA"},
			"311": {"town":"Warren","MPO":"Central Massachusetts","RTA":"WRTA"},
			"312": {"town":"Warwick","MPO":"Franklin","RTA":"FRTA"},
			"313": {"town":"Washington","MPO":"Berkshire","RTA":"NONE"},
			"314": {"town":"Watertown","MPO":"Boston Region","RTA":"MBTA"},
			"315": {"town":"Wayland","MPO":"Boston Region","RTA":"MBTA"},
			"316": {"town":"Webster","MPO":"Central Massachusetts","RTA":"WRTA"},
			"317": {"town":"Wellesley","MPO":"Boston Region","RTA":"MBTA"},
			"318": {"town":"Wellfleet","MPO":"Cape Cod","RTA":"CCRTA"},
			"319": {"town":"Wendell","MPO":"Franklin","RTA":"FRTA"},
			"320": {"town":"Wenham","MPO":"Boston Region","RTA":"MBTA"},
			"321": {"town":"West Boylston","MPO":"Central Massachusetts","RTA":"WRTA"},
			"322": {"town":"West Bridgewater","MPO":"Old Colony","RTA":"BAT"},
			"323": {"town":"West Brookfield","MPO":"Central Massachusetts","RTA":"WRTA"},
			"324": {"town":"West Newbury","MPO":"Merrimack Valley","RTA":"MVRTA"},
			"325": {"town":"West Springfield","MPO":"Pioneer Valley","RTA":"PVTA"},
			"326": {"town":"West Stockbridge","MPO":"Berkshire","RTA":"NONE"},
			"327": {"town":"West Tisbury","MPO":"Martha's Vineyard","RTA":"VTA"},
			"328": {"town":"Westborough","MPO":"Central Massachusetts","RTA":"WRTA"},
			"329": {"town":"Westfield","MPO":"Pioneer Valley","RTA":"PVTA"},
			"330": {"town":"Westford","MPO":"Northern Middlesex","RTA":"LRTA"},
			"331": {"town":"Westhampton","MPO":"Pioneer Valley","RTA":"FRTA"},
			"332": {"town":"Westminster","MPO":"Montachusett","RTA":"MRTA"},
			"333": {"town":"Weston","MPO":"Boston Region","RTA":"MBTA"},
			"334": {"town":"Westport","MPO":"Southeastern Massachusetts","RTA":"SRTA"},
			"335": {"town":"Westwood","MPO":"Boston Region","RTA":"MBTA"},
			"336": {"town":"Weymouth","MPO":"Boston Region","RTA":"MBTA"},
			"337": {"town":"Whately","MPO":"Franklin","RTA":"FRTA"},
			"338": {"town":"Whitman","MPO":"Old Colony","RTA":"BAT"},
			"339": {"town":"Wilbraham","MPO":"Pioneer Valley","RTA":"PVTA"},
			"340": {"town":"Williamsburg","MPO":"Pioneer Valley","RTA":"PVTA"},
			"341": {"town":"Williamstown","MPO":"Berkshire","RTA":"BRTA"},
			"342": {"town":"Wilmington","MPO":"Boston Region","RTA":"MBTA"},
			"343": {"town":"Winchendon","MPO":"Montachusett","RTA":"MRTA"},
			"344": {"town":"Winchester","MPO":"Boston Region","RTA":"MBTA"},
			"345": {"town":"Windsor","MPO":"Berkshire","RTA":"NONE"},
			"346": {"town":"Winthrop","MPO":"Boston Region","RTA":"MBTA"},
			"347": {"town":"Woburn","MPO":"Boston Region","RTA":"MBTA"},
			"348": {"town":"Worcester","MPO":"Central Massachusetts","RTA":"WRTA"},
			"349": {"town":"Worthington","MPO":"Pioneer Valley","RTA":"FRTA"},
			"350": {"town":"Wrentham","MPO":"Boston Region","RTA":"NONE"},
			"351": {"town":"Yarmouth","MPO":"Cape Cod","RTA":"CCRTA"}
		};

});
